// <auto-generated />
using System;
using BancoQuestoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BancoQuestoes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904215636_AdicionarConfiguracaoIa")]
    partial class AdicionarConfiguracaoIa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BancoQuestoes.Models.AlternativaQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<int>("QuestaoMultiplaEscolhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoMultiplaEscolhaId");

                    b.ToTable("AlternativasQuestao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.AreaCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeNormalizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Nome\")", true);

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("AreasCurso");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ConfiguracaoIa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyNuvem")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrlLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("boolean");

                    b.Property<string>("ModeloLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeloNuvem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeoutSegundos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesIa");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaCursoId")
                        .HasColumnType("integer");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaCursoId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("BancoQuestoes.Models.CursoDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("integer");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("CursoId", "DisciplinaId")
                        .IsUnique();

                    b.ToTable("CursosDisciplinas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CriadoPorId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("text");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoConteudo")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SistemaPeriodos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Semestral");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ItemMatrizReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("MatrizReferenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("MatrizReferenciaId");

                    b.HasIndex("Tipo");

                    b.HasIndex("MatrizReferenciaId", "Codigo")
                        .IsUnique();

                    b.ToTable("ItensMatrizReferencia");
                });

            modelBuilder.Entity("BancoQuestoes.Models.LacunaResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoLacunasId")
                        .HasColumnType("integer");

                    b.Property<string>("RespostaEsperada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoLacunasId");

                    b.ToTable("LacunasRespostas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.MatrizReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<int?>("AreaCursoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Edicao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orgao")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFonte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.HasIndex("AreaCursoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.ToTable("MatrizesReferencia");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ParAssociacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correspondente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoAssociacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Termo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoAssociacaoId");

                    b.ToTable("ParesAssociacao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Prova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<int?>("Bimestre")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPorId")
                        .HasColumnType("text");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DataAplicacao")
                        .HasColumnType("date");

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MatrizReferenciaId")
                        .HasColumnType("integer");

                    b.Property<bool>("MostrarValorNoEnunciado")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int?>("Semestre")
                        .HasColumnType("integer");

                    b.Property<int?>("TempoEstimadoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<string>("TipoEscopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Disciplina");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("MatrizReferenciaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ProvaDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PercentualPlanejado")
                        .HasColumnType("integer");

                    b.Property<int>("ProvaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProvaId", "DisciplinaId")
                        .IsUnique();

                    b.ToTable("ProvasDisciplinas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ProvaQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("ProvaId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("ProvaId", "QuestaoId")
                        .IsUnique();

                    b.ToTable("ProvasQuestoes");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("AssuntoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bloom")
                        .HasColumnType("text");

                    b.Property<string>("CodigoProvaOrigem")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPorId")
                        .HasColumnType("text");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explicacao")
                        .HasColumnType("text");

                    b.Property<string>("NumeroOriginal")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("SecaoEnade")
                        .HasColumnType("text");

                    b.Property<string>("TipoQuestao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("Questoes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoAreaCurso", b =>
                {
                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("AreaCursoId")
                        .HasColumnType("integer");

                    b.HasKey("QuestaoId", "AreaCursoId");

                    b.HasIndex("AreaCursoId");

                    b.ToTable("QuestoesAreasCurso", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("QuestoesHistorico");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alinhamento")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("LarguraPercentual")
                        .HasColumnType("integer");

                    b.Property<string>("Legenda")
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TextoAlternativo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("QuestoesImagens");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoItemMatriz", b =>
                {
                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemMatrizReferenciaId")
                        .HasColumnType("integer");

                    b.HasKey("QuestaoId", "ItemMatrizReferenciaId");

                    b.HasIndex("ItemMatrizReferenciaId");

                    b.ToTable("QuestoesItensMatriz", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeNormalizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Nome\")", true);

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int?>("Bimestre")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPorId")
                        .HasColumnType("text");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestaoTag", b =>
                {
                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("QuestaoId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("QuestoesTags", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoAssociacao", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.ToTable("QuestoesAssociacao", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoCertoErrado", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.Property<bool>("RespostaCorreta")
                        .HasColumnType("boolean");

                    b.ToTable("QuestoesCertoErrado", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoDiscursiva", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.Property<string>("CriterioAvaliacao")
                        .HasColumnType("text");

                    b.Property<string>("RespostaEsperada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("QuestoesDiscursivas", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoLacunas", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.ToTable("QuestoesLacunas", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoMultiplaEscolha", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.Property<char>("RespostaCorreta")
                        .HasColumnType("character(1)");

                    b.ToTable("QuestoesMultiplaEscolha", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoNumerica", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.Property<decimal>("RespostaEsperada")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tolerancia")
                        .HasColumnType("numeric");

                    b.ToTable("QuestoesNumericas", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoRespostaBreve", b =>
                {
                    b.HasBaseType("BancoQuestoes.Models.Questao");

                    b.Property<string>("RespostaEsperada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("QuestoesRespostaBreve", (string)null);
                });

            modelBuilder.Entity("BancoQuestoes.Models.AlternativaQuestao", b =>
                {
                    b.HasOne("BancoQuestoes.Models.QuestaoMultiplaEscolha", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoMultiplaEscolhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ApplicationUser", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Assunto", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Disciplina", "Disciplina")
                        .WithMany("Assuntos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Curso", b =>
                {
                    b.HasOne("BancoQuestoes.Models.AreaCurso", "AreaCurso")
                        .WithMany()
                        .HasForeignKey("AreaCursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BancoQuestoes.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCurso");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.CursoDisciplina", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Disciplina", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ItemMatrizReferencia", b =>
                {
                    b.HasOne("BancoQuestoes.Models.MatrizReferencia", "MatrizReferencia")
                        .WithMany("Itens")
                        .HasForeignKey("MatrizReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatrizReferencia");
                });

            modelBuilder.Entity("BancoQuestoes.Models.LacunaResposta", b =>
                {
                    b.HasOne("BancoQuestoes.Models.QuestaoLacunas", "Questao")
                        .WithMany("Lacunas")
                        .HasForeignKey("QuestaoLacunasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.MatrizReferencia", b =>
                {
                    b.HasOne("BancoQuestoes.Models.AreaCurso", "AreaCurso")
                        .WithMany()
                        .HasForeignKey("AreaCursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BancoQuestoes.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaCurso");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ParAssociacao", b =>
                {
                    b.HasOne("BancoQuestoes.Models.QuestaoAssociacao", "Questao")
                        .WithMany("Pares")
                        .HasForeignKey("QuestaoAssociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Prova", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.HasOne("BancoQuestoes.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BancoQuestoes.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BancoQuestoes.Models.MatrizReferencia", "MatrizReferencia")
                        .WithMany()
                        .HasForeignKey("MatrizReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BancoQuestoes.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");

                    b.Navigation("MatrizReferencia");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ProvaDisciplina", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Prova", "Prova")
                        .WithMany("ProvaDisciplinas")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Prova");
                });

            modelBuilder.Entity("BancoQuestoes.Models.ProvaQuestao", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Prova", "Prova")
                        .WithMany("ProvaQuestoes")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prova");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Questao", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Assunto", "Assunto")
                        .WithMany("Questoes")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.ApplicationUser", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.Navigation("Assunto");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoAreaCurso", b =>
                {
                    b.HasOne("BancoQuestoes.Models.AreaCurso", "AreaCurso")
                        .WithMany()
                        .HasForeignKey("AreaCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCurso");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoHistorico", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Questao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoImagem", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", "Questao")
                        .WithMany("Imagens")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoItemMatriz", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ItemMatrizReferencia", "ItemMatrizReferencia")
                        .WithMany()
                        .HasForeignKey("ItemMatrizReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMatrizReferencia");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Turma", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.HasOne("BancoQuestoes.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BancoQuestoes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestaoTag", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoQuestoes.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoAssociacao", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoAssociacao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoCertoErrado", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoCertoErrado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoDiscursiva", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoDiscursiva", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoLacunas", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoLacunas", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoMultiplaEscolha", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoMultiplaEscolha", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoNumerica", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoNumerica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoRespostaBreve", b =>
                {
                    b.HasOne("BancoQuestoes.Models.Questao", null)
                        .WithOne()
                        .HasForeignKey("BancoQuestoes.Models.QuestaoRespostaBreve", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoQuestoes.Models.Assunto", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Disciplina", b =>
                {
                    b.Navigation("Assuntos");
                });

            modelBuilder.Entity("BancoQuestoes.Models.MatrizReferencia", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Prova", b =>
                {
                    b.Navigation("ProvaDisciplinas");

                    b.Navigation("ProvaQuestoes");
                });

            modelBuilder.Entity("BancoQuestoes.Models.Questao", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoAssociacao", b =>
                {
                    b.Navigation("Pares");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoLacunas", b =>
                {
                    b.Navigation("Lacunas");
                });

            modelBuilder.Entity("BancoQuestoes.Models.QuestaoMultiplaEscolha", b =>
                {
                    b.Navigation("Alternativas");
                });
#pragma warning restore 612, 618
        }
    }
}
